@startuml
!theme cerulean
actor User #438dd5
participant "Product Detail View" as product_detail_view
participant "Cart Controller" as cart_controller

User -> product_detail_view :1. Click on add to cart
product_detail_view -> product_detail_view :isLogin

alt Yes
	product_detail_view --> cart_controller :2.1. Add new item
	cart_controller -> Service :3. Mapping AddNewItem()
	Service --> Repository :4. Find Cart Id
	Repository -> Service :5. Cart
	Service --> Repository :6. Find Product Id
	Repository -> Service :7. Product
    Service --> Database :8. New Cart Item
    Database --> Service :9. Cart Item
    Service --> Repository :10. Save
else No
	product_detail_view ->product_detail_view :2.2. Can't Add Dialog()
end
@enduml