@startuml(id=AddProductComponent)
title Online Food Ordering System - API Application - Components

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam rectangle<<33>> {
  BackgroundColor #438dd5
  FontColor #000000
  BorderColor #2e6295
}
skinparam rectangle<<34>> {
  BackgroundColor #438dd5
  FontColor #000000
  BorderColor #2e6295
}
skinparam rectangle<<35>> {
  BackgroundColor #438dd5
  FontColor #000000
  BorderColor #2e6295
}
skinparam rectangle<<36>> {
  BackgroundColor #438dd5
  FontColor #000000
  BorderColor #2e6295
}
skinparam rectangle<<9>> {
  BackgroundColor #438dd5
  FontColor #000000
  BorderColor #2e6295
}
skinparam database<<43>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}
database "==Database\n<size:10>[Container: SQL Server 2019]</size>\n\nStores data customer states" <<43>> as 43
package "API Application\n[Container: C# and ASP.NET core]" {
  rectangle "==Add Product Model\n<size:10>[Component: ASP.NET Core Rest Model]</size>\n\nProvide cached data model of product by admin" <<35>> as 35
  rectangle "==Product Controller\n<size:10>[Component: ASP.NET Core Rest Controller]</size>\n\nProvide API interface Product" <<33>> as 33
  rectangle "==Product Model\n<size:10>[Component: ASP.NET Core Rest Model]</size>\n\nProvide data model of product and interfce to database" <<34>> as 34
  rectangle "==Service\n<size:10>[Component: ASP.NET Core Rest Service]</size>\n\nHanding when called" <<36>> as 36
}
package "Web Application\n[Container: JS and VueJS]" {
  rectangle "==Product Manage View\n<size:10>[Component: VueJS and JS]</size>\n\nProduct Data Processing" <<9>> as 9
}
33 .[#707070,thickness=2].> 36 : "Mapping Route Add Product"
9 .[#707070,thickness=2].> 33 : "Makes API calls to\n<size:8>[HTTP]</size>"
34 .[#707070,thickness=2].> 43 : "Read from and Write to"
36 .[#707070,thickness=2].> 35 : "Call Model Add Product"
36 .[#707070,thickness=2].> 34 : "Call Model Product"
@enduml